test: Increase the ULP allowed against musl for `tanhf`
    thread 'musl_random_tanhf' (76230) panicked at libm-test/tests/compare_built_musl.rs:26:50:
    called `Result::unwrap()` on an `Err` value: 
        input:    (0.24503659,)
        as hex:   (0x1.f5d5bep-3,)
        as bits:  (0x1.f5d5bep-3,)
        expected: 0.24024732             0x1.ec06cap-3 0x1.ec06cap-3
        actual:   0.24024737             0x1.ec06d0p-3 0x1.ec06d0p-3

    Caused by:
        ulp 3 > 2

    thread 'musl_quickspace_tanhf' (38650234) panicked at libm-test/tests/compare_built_musl.rs:26:50:
    called `Result::unwrap()` on an `Err` value:
        input:    (0.19125812,)
        as hex:   (0x1.87b256p-3,)
        as bits:  (0x1.87b256p-3,)
        expected: 0.18895967             0x1.82fd4ap-3 0x1.82fd4ap-3
        actual:   0.18895972             0x1.82fd50p-3 0x1.82fd50p-3

    Caused by:
        ulp 3 > 2